
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 20 22:13:57 IST 2023
//----------------------------------------------------

package frontend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EVENTS = 30;
  public static final int TRIGGER = 25;
  public static final int GE = 35;
  public static final int STATE = 21;
  public static final int STRLITERAL = 4;
  public static final int HASH = 15;
  public static final int LPAREN = 7;
  public static final int SHELL = 52;
  public static final int RPAREN = 8;
  public static final int NOT = 44;
  public static final int SEMICOLON = 11;
  public static final int AND = 31;
  public static final int LT = 38;
  public static final int UMIN = 43;
  public static final int TYPE = 49;
  public static final int INTCONST = 3;
  public static final int OR = 32;
  public static final int COMMA = 13;
  public static final int DIV = 42;
  public static final int RTRI = 10;
  public static final int EXIT = 29;
  public static final int ASSIGN = 16;
  public static final int IF = 18;
  public static final int GUARD = 26;
  public static final int DOT = 14;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int TRUE = 45;
  public static final int REGION = 53;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int ADD = 40;
  public static final int ACTION = 27;
  public static final int EQ = 33;
  public static final int COLON = 12;
  public static final int ENTRY = 28;
  public static final int LBRACE = 5;
  public static final int ELSE = 19;
  public static final int FUNCTIONS = 50;
  public static final int HISTORY = 51;
  public static final int WHILE = 17;
  public static final int RBRACE = 6;
  public static final int NE = 34;
  public static final int TYPES = 48;
  public static final int FALSE = 46;
  public static final int STRUCT = 47;
  public static final int SRC = 23;
  public static final int GT = 36;
  public static final int TRANSITION = 22;
  public static final int LTRI = 9;
  public static final int SUB = 39;
  public static final int DEST = 24;
  public static final int STATECHART = 20;
  public static final int IDENTIFIER = 2;
}

